name: Deployment Pipeline

on:
  push:
    branches:
      - feature-201900042

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ir a Frontend
        run: cd Frontend

      - name: Instalando dependencias
        run: npm install --no-audit --no-fund --no-optional
        working-directory: Frontend

      - name: Lint
        run: npm run eslint
        working-directory: Frontend

      - name: ejecucion de pruebas
        run: npm run dev
        working-directory: Frontend

      - name: Build
        run: npm run build
        working-directory: Frontend